### ISSUE TITLE
Milestone 2: Data Analysis and Final Report

### ISSUE THREAD

**Issue by shlrley** [UBC-MDS/maternal_health_risk_predictor#10]
**Tasks:**
- [ ] Write a script that reads the downloaded data and performs data cleaning/pre-processing, transforming, and/or splitting: **Lennon**
- [ ] Write a script which creates exploratory data visualization(s) and table(s) (USING THE PREPROCESSED DATA) that are useful to help the reader/consumer understand that data set: **Lennon**
- [ ] Write a script that performs some statistical or machine learning analysis (USING THE PREPROCESSED DATA) and summarizes the results as a figure(s) and a table(s): **Shirley**
- [ ] Write a literate code document which presents your analysis and findings: **Dudu**
- [ ] Create a bash script that runs everything above (also replicate this in our 'Usage' section of the README.md): **Dudu**

**Comment by shlrley** [comment]
**Meeting 1 (Tuesday, November 22, 2022):**

**Comment by lennonay** [comment]
Preprocessing: Lennon by Tuesday
EDA: Lennon by Wednesday
Modelling: Shirley by Thursday
Report: Dudu by Friday

**Comment by shlrley** [comment]
**Meeting 2 (Thursday, November 24, 2022):**

Shirley's tasks: 
- [x] Hyperparameter optimization on Decision Tree model 
- [ ] Format tables and graphs 
- [ ] Double check scores
- [x] Save tables as .csv and output images as png, model as pickle (?), save into new folder 
- [x] Wrap everything up in a script 
- [x] Add dependencies 
- [ ] Run usage to make sure everything works 
- [ ] Write doc strings and tests for all functions (also DRY coding + write to txt instead of print dt scores)
- [ ] Key features in decision trees

Dudu's tasks:
- [x] Review DSCI 522 lecture 4 (final report using .Rmd)
- [x] Work on final report 

Lennon's tasks: 
- [x] Improve EDA script 
- [x] Save outputs as pngs

**Comment by shlrley** [comment]
To run model script: 
`python src/fit_maternal_risk_predict_model.py --train_df_path='data/processed/train_df.csv' --test_df_path='data/processed/test_df.csv' --output_dir_path='src/maternal_risk_model_figures/'`

**Comment by shlrley** [comment]
(DRAFT) **Meeting 3 (Friday, November 25, 2022):**

**ANALYSIS CODE**
1. Download script 
2. Preprocessing script 
3. EDA script 
4. Model fitting script 
- [ ] Only have two inputs 

5. Final Report (Dudu):
- Limitations: 
not searching all hyperparameters, decision tree optimizing at the beginning?
