### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by mohamad-amin** [UBC-MDS/maternal_health_risk_predictor#23]
Thank you for your great work! 

## Regarding EDA:

- [x] Seems like some pictures are missing, and are shown as png blocks without any actual image. I suppose you forgot to include some images, is that the case? [The document contains some problem. For instance, a plot that is not rendered correctly. -1]
- [x] It could be useful to do more analysis and try to see which model would be more useful based on the properties of the data that you have. [Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing). -1 writing]

## Regarding prediction:
- [x] I would suggest adding random forest to your set of models, as typically tree-based ensemble methods work better on these kinds of datasets. 
- [x] You might need to do some feature engineering before feeding the data into different models. For instance, normalizing the features before feeding them into SVM or LogisticRegression. [-2, needs more reasoning]

## Other:
- [x] DS_STORE should not be commited. [-1]

Thanks.

**Comment by lennonay** [comment]
Hi Amin, thanks a lot for your feedback. 
Regarding the missing pictures of the EDA, do you mean that the charts in the ipynb is missing?

**Comment by mohamad-amin** [comment]
Hi, no, I mean in this doc: https://github.com/UBC-MDS/maternal_health_risk_predictor/blob/main/doc/final_report.md.
