### ISSUE TITLE
Milestone 3 tasks for Shirley

### ISSUE THREAD

**Issue by shlrley** [UBC-MDS/maternal_health_risk_predictor#27]
- [x] Makefile (test model and final report) 
- [x] Add pickle to dependencies
- [x] Edit final report

**Comment by shlrley** [comment]
**To run predict_model_on_test.py:**

python src/predict_model_on_test.py --bestmodel_path='src/maternal_risk_model_figures/bestmodel.pkl' --test_df_path='data/processed/test_df.csv' --output_dir_path='src/maternal_risk_model_figures/'
