### ISSUE TITLE
Milestone 2 - Feedback

### ISSUE THREAD

**Issue by danielramandi** [UBC-MDS/maternal_health_risk_predictor#35]
Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work! Below we list some specific feedback you can use to improve your project. We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.

**1. Analysis code and scripts**

- [x] #37

**Comment:** It is not a good practice to define functions inside your main() function. All functions should be defined outside (preferably before) the main function. Some of the scripts follow this pattern, but some do not. 

- [ ] There are cases of functions that do not check for proper input and/or do not provide useful error messages. -1 mechanics

**Comment:** Reproducible scripts should always check for the inputs (type, size, etc.) and provide error messages if an input is missing or is not of the correct type.

- [ ] One or more function documentations are missing -5 quality

**Comment:** Add at least one sentence on what each function does (preferably mention the type of input and output).

- [ ] There is no documentation for tests. It is not clear what the tests are testing. -3 quality

**Comment:** some functions do not have proper tests, or are not documented. You can use unit testing to solve this. [Here](https://towardsdatascience.com/unit-testing-in-r-68ab9cc8d211)’s a nice article on unit testing. But simply, you can check for input type discrepancies and raise proper errors manually.  

**2. Submission expectations**

- [x] Please provide the link to the release as https://github.com/UBC-MDS/REPOSITORY/tree/VERSION (replacing REPOSITORY and VERSION with the correct ones for your project version for each milestone). This makes it a lot easier for someone to just visit the repository as it was at that point in the project's history. -3 mechanics

--------------------------------------
**Overall comment:** The project and the reports are well-designed and informative. The usage section is very reproducible and easy to follow. Here are some small modifications that I thought could help: 

- [x] I suggest using HTTPS for the cloning command, as it would not require the user to set up SSH prior to cloning. 
- [x] There is also a mention of Table 2 in the text of the report, but the code has been commented out. 
- [ ] Finally, I suggest reporting the baseline score (with dummyclassifier) in your READ ME (where you report the score of the decision tree) to make it easier to assess the performance of the model. 
Well done and good luck!

**Comment by shlrley** [comment]
Thank you very much Daniel for your feedback, all the suggestions are very helpful and we will be sure to implement them!
