### ISSUE TITLE
Milestone 4 Tasks

### ISSUE THREAD

**Issue by shlrley** [UBC-MDS/maternal_health_risk_predictor#43]
**Dudu**

- [x] Review lecture 6
- [x] Create Dependency diagram of the Makefile [(task)](https://pages.github.ubc.ca/MDS-2022-23/DSCI_522_dsci-workflows_students/materials/assignments/milestone4.html#dependency-diagram-of-the-makefile)

**Shirley**

- [ ] Review lecture 6 and 7 
- [ ] Make project reproducible (to the max) with Docker 
- [ ] Improve some feedback given 

**Lennon**

- [ ] Improve the project based on the feedback received
